// 自动生成（parse_essays.py 从 408 PDF 解析，勿手改）
export const ESSAY_2022_2026 = [
  { id: "es2022_41",
    year: 2022,
    subject: "数据结构",
    type: 'essay',
    no: 41,
    stem: "二叉树结点的纟割勾如下·\ntypedef stru ct{\nEIemType Sqlistdata[MaxSize];\nint num;\n}Sqlist; 用数组保存二叉树， 每个结点保存正整数， 空节点的值为一1 ， 设计一个高效算法， 判断二叉树早否大二树．\n（ 1 ） 给出算法的基本设计思想（ 2 ） 根据设计思想采用C 或者C + + 语言描述算氵去关键之处给出注释",
    parts: [{ no: "", prompt: "", answer: "： （ 1 ） 判断二叉搜索树， 只需要判而亥树的中序遍历是否是升序序列即可， 可采用递归方式中序遍历。 （ 注： 1. 根结点在数组0 下标处， 所以i 结点的左几子是2 * i + 1 ， 右丿l, 子是2 * i + 2\n（ 2 ） 解法一， 中序递归（ 推荐） ：\nb00 《 T=true;\nint k=O;\nvoid inorder(Sqlist a,int i)\nif (i>a.num 《 丨a.Sqlistdata[ 刂=．1 目(T) return;\ninorder(a,i*2+1);\n/ ／ 左子树不存在或己经确定不是二叉搜索树了/ / 访问左子树if (k>a.Sqlistdata [ i * 2 + 1 ] ） 仃=false; retu rn;}\nk=a.Sqlistdata[i*2+1];\ninorder(a,i* 2 + 2);\nbOOl ans(Sqlist a)\ni norder(a,O);\nreturn T;\n/ / 访问右子树解法二， 区间放缩（ 这里是先序） ， 如果当前子树的值范围是[ a ， b ] ， 根的值为c ， 那左子树值可能范围是[ a 孓], 右子树值可能范围是℃ b ] ：\nbOOl T=true,\nint k=O,\nVOid preorder(Sqlist a,int i,int Min,int Max)\nif (i>a.num 《 | a.Sqlistdata[i]=-1 目仃） return;\nif (a.Sqlistdata[i]<Min 《 | a.Sqlistdata[i]>Max) 仃=fa lse; return;}\npreorder(a,i*2+1,Min,a.Sqlistdata[i]);\npreorder(a,i*2+2,a.Sqlistdata[i], M ax);\nb00 《 ans(Sqlist a)\n/ / 当前子树根结点值不在范围内/ / 访问左子树/ / 访问右子树preorder(a,O,O, MAXINT);\nreturn T;\n& 解答：\n//MAXINT 是最大整数，\nONMAXINT 对二叉排序树来说， 其中序遍历序列为一个递增有序序列。 因此， 对给定的二叉树进行中序遍历， 若始终能保持前一个值比后一个值小， 则说明该二叉树是一棵二叉排序树。 算法实现如下：\nKeyType predt=—32767 ；\nint JudgeBST (BiTree (t) （\nint b b2 ；\nif (bt=NULL)\n2022 年数据结构考研复习指导return 1 ；\nelse(\n//predt 为全局变量， 保存当前结点中序前驱的值， 初值为一/ / 空树b1—JudgeBST (bt—>lchild) ；\nif （ bl = = 0 《 《 predt>=bt—>data ）\nreturn 0 ；\npredt—bt—>data ；\nb2=JudgeBST (bt—>rchild)\nreturn b2 ；\n42 ，\n／ / 判断左子树是否是二叉排序树／ / 若左子树返回值为0 或前驱大于等于当前结点/ / 则不是二叉排序树/ / 保存当前结点的关键字/ / 判断右了树/ / 返回右子树的结果数组M 有从n 个数（ n > 100000 ） ， 从中畢10 个最/ 」 啲数， 要求尽可能少的比较次数（ 1 ） 用语言描述算法， 不用写代码（ 2 ） 给出空间和时间复杂度答案：\n（ 1 ） 解氵去一： 因为10 < < n ， 只需要找到10 个最小值， 可以考虑选择类排序（ 简单选择/ 堆， 考场上写简单选择更简单， 堆的比较次数不好判断） 选择排序： 进行k 趟， 每趟循环扫描一遍， 从剩余未选择的数中选择一个最小的数和a[i-l] 交换（ 第i 趟是与a [ i 一1 ] 交换), 进行10 趟之后a [ 0 卜a [ 9 ] 即所求。 解氵去二： ． 建堆& 4 ． 2 堆排序" }],
    analysis: "： （ 1 ） 判断二叉搜索树， 只需要判而亥树的中序遍历是否是升序序列即可， 可采用递归方式中序遍历。 （ 注： 1. 根结点在数组0 下标处， 所以i 结点的左几子是2 * i + 1 ， 右丿l, 子是2 * i + 2\n（ 2 ） 解法一， 中序递归（ 推荐） ：\nb00 《 T=true;\nint k=O;\nvoid inorder(Sqlist a,int i)\nif (i>a.num 《 丨a.Sqlistdata[ 刂=．1 目(T) return;\ninorder(a,i*2+1);\n/ ／ 左子树不存在或己经确定不是二叉搜索树了/ / 访问左子树if (k>a.Sqlistdata [ i * 2 + 1 ] ） 仃=false; retu rn;}\nk=a.Sqlistdata[i*2+1];\ninorder(a,i* 2 + 2);\nbOOl ans(Sqlist a)\ni norder(a,O);\nreturn T;\n/ / 访问右子树解法二， 区间放缩（ 这里是先序） ， 如果当前子树的值范围是[ a ， b ] ， 根的值为c ， 那左子树值可能范围是[ a 孓], 右子树值可能范围是℃ b ] ：\nbOOl T=true,\nint k=O,\nVOid preorder(Sqlist a,int i,int Min,int Max)\nif (i>a.num 《 | a.Sqlistdata[i]=-1 目仃） return;\nif (a.Sqlistdata[i]<Min 《 | a.Sqlistdata[i]>Max) 仃=fa lse; return;}\npreorder(a,i*2+1,Min,a.Sqlistdata[i]);\npreorder(a,i*2+2,a.Sqlistdata[i], M ax);\nb00 《 ans(Sqlist a)\n/ / 当前子树根结点值不在范围内/ / 访问左子树/ / 访问右子树preorder(a,O,O, MAXINT);\nreturn T;\n& 解答：\n//MAXINT 是最大整数，\nONMAXINT 对二叉排序树来说， 其中序遍历序列为一个递增有序序列。 因此， 对给定的二叉树进行中序遍历， 若始终能保持前一个值比后一个值小， 则说明该二叉树是一棵二叉排序树。 算法实现如下：\nKeyType predt=—32767 ；\nint JudgeBST (BiTree (t) （\nint b b2 ；\nif (bt=NULL)\n2022 年数据结构考研复习指导return 1 ；\nelse(\n//predt 为全局变量， 保存当前结点中序前驱的值， 初值为一/ / 空树b1—JudgeBST (bt—>lchild) ；\nif （ bl = = 0 《 《 predt>=bt—>data ）\nreturn 0 ；\npredt—bt—>data ；\nb2=JudgeBST (bt—>rchild)\nreturn b2 ；\n42 ，\n／ / 判断左子树是否是二叉排序树／ / 若左子树返回值为0 或前驱大于等于当前结点/ / 则不是二叉排序树/ / 保存当前结点的关键字/ / 判断右了树/ / 返回右子树的结果数组M 有从n 个数（ n > 100000 ） ， 从中畢10 个最/ 」 啲数， 要求尽可能少的比较次数（ 1 ） 用语言描述算法， 不用写代码（ 2 ） 给出空间和时间复杂度答案：\n（ 1 ） 解氵去一： 因为10 < < n ， 只需要找到10 个最小值， 可以考虑选择类排序（ 简单选择/ 堆， 考场上写简单选择更简单， 堆的比较次数不好判断） 选择排序： 进行k 趟， 每趟循环扫描一遍， 从剩余未选择的数中选择一个最小的数和a[i-l] 交换（ 第i 趟是与a [ i 一1 ] 交换), 进行10 趟之后a [ 0 卜a [ 9 ] 即所求。 解氵去二： ． 建堆& 4 ． 2 堆排序",
    tags: ["数据结构"] },
]
