// qbankMathProblem.js —— 数学一解答题（高数 8 / 线代 8 / 概率 8，带详细解答，自动生成勿手改）
export const MATH_PROBLEMS = [
  { id: "pg_mathp_000",
    year: 2026,
    subject: '数学一',
    type: 'essay',
    no: 0,
    stem: "计算极限 lim(x→0) sin(3x)/x。",
    parts: [{ no: "", prompt: "", answer: "由重要极限 lim(x→0) sin x / x = 1，得 lim(x→0) sin(3x)/x = lim(x→0) 3·sin(3x)/(3x) = 3·1 = 3。答案：3。" }],
    analysis: "由重要极限 lim(x→0) sin x / x = 1，得 lim(x→0) sin(3x)/x = lim(x→0) 3·sin(3x)/(3x) = 3·1 = 3。答案：3。",
    tags: ["数学解答", "高数"],
    source: 'practice' },
  { id: "pg_mathp_001",
    year: 2026,
    subject: '数学一',
    type: 'essay',
    no: 0,
    stem: "设 y = x²·eˣ，求 dy/dx。",
    parts: [{ no: "", prompt: "", answer: "由乘积法则求导：(x²·eˣ)的导数为 2x·eˣ + x²·eˣ = x·eˣ(x+2)。答案：dy/dx = x·eˣ(x+2)。" }],
    analysis: "由乘积法则求导：(x²·eˣ)的导数为 2x·eˣ + x²·eˣ = x·eˣ(x+2)。答案：dy/dx = x·eˣ(x+2)。",
    tags: ["数学解答", "高数"],
    source: 'practice' },
  { id: "pg_mathp_002",
    year: 2026,
    subject: '数学一',
    type: 'essay',
    no: 0,
    stem: "计算不定积分 ∫ x·eˣ dx。",
    parts: [{ no: "", prompt: "", answer: "分部积分：令 u=x, dv=eˣdx，则 du=dx, v=eˣ。∫ x·eˣ dx = x·eˣ − ∫ eˣ dx = (x−1)·eˣ + C。答案：(x−1)eˣ + C。" }],
    analysis: "分部积分：令 u=x, dv=eˣdx，则 du=dx, v=eˣ。∫ x·eˣ dx = x·eˣ − ∫ eˣ dx = (x−1)·eˣ + C。答案：(x−1)eˣ + C。",
    tags: ["数学解答", "高数"],
    source: 'practice' },
  { id: "pg_mathp_003",
    year: 2026,
    subject: '数学一',
    type: 'essay',
    no: 0,
    stem: "判定级数 Σ(n=1→∞) 1/n² 的敛散性。",
    parts: [{ no: "", prompt: "", answer: "这是 p-级数 Σ1/n^p，p=2>1，由 p-级数判别法知该级数收敛（且收敛到 π²/6）。答案：收敛。" }],
    analysis: "这是 p-级数 Σ1/n^p，p=2>1，由 p-级数判别法知该级数收敛（且收敛到 π²/6）。答案：收敛。",
    tags: ["数学解答", "高数"],
    source: 'practice' },
  { id: "pg_mathp_004",
    year: 2026,
    subject: '数学一',
    type: 'essay',
    no: 0,
    stem: "求微分方程 y' = 2x 满足 y(0)=1 的特解。",
    parts: [{ no: "", prompt: "", answer: "两边积分：y = ∫2x dx = x² + C。代入 y(0)=1 得 C=1。答案：y = x² + 1。" }],
    analysis: "两边积分：y = ∫2x dx = x² + C。代入 y(0)=1 得 C=1。答案：y = x² + 1。",
    tags: ["数学解答", "高数"],
    source: 'practice' },
  { id: "pg_mathp_005",
    year: 2026,
    subject: '数学一',
    type: 'essay',
    no: 0,
    stem: "求函数 f(x)=x³−3x 的极值。",
    parts: [{ no: "", prompt: "", answer: "求导得 f 的导数为 3x²−3=3(x−1)(x+1)，驻点 x=±1；二阶导数 6x：x=−1 时 <0 取极大 f(−1)=2，x=1 时 >0 取极小 f(1)=−2。答案：极大 f(−1)=2，极小 f(1)=−2。" }],
    analysis: "求导得 f 的导数为 3x²−3=3(x−1)(x+1)，驻点 x=±1；二阶导数 6x：x=−1 时 <0 取极大 f(−1)=2，x=1 时 >0 取极小 f(1)=−2。答案：极大 f(−1)=2，极小 f(1)=−2。",
    tags: ["数学解答", "高数"],
    source: 'practice' },
  { id: "pg_mathp_006",
    year: 2026,
    subject: '数学一',
    type: 'essay',
    no: 0,
    stem: "计算二重积分 ∬_D (x+y) dσ，其中 D={(x,y)|0≤x≤1, 0≤y≤1}。",
    parts: [{ no: "", prompt: "", answer: "∬_D (x+y) dxdy = ∫₀¹∫₀¹ (x+y) dy dx = ∫₀¹ (x·1 + 1/2) dx = (1/2 + 1/2) = 1。答案：1。" }],
    analysis: "∬_D (x+y) dxdy = ∫₀¹∫₀¹ (x+y) dy dx = ∫₀¹ (x·1 + 1/2) dx = (1/2 + 1/2) = 1。答案：1。",
    tags: ["数学解答", "高数"],
    source: 'practice' },
  { id: "pg_mathp_007",
    year: 2026,
    subject: '数学一',
    type: 'essay',
    no: 0,
    stem: "求曲线 y=x²、x 轴与直线 x=1 所围平面图形的面积。",
    parts: [{ no: "", prompt: "", answer: "S = ∫₀¹ x² dx = x³/3 |₀¹ = 1/3。答案：1/3。" }],
    analysis: "S = ∫₀¹ x² dx = x³/3 |₀¹ = 1/3。答案：1/3。",
    tags: ["数学解答", "高数"],
    source: 'practice' },
  { id: "pg_mathp_008",
    year: 2026,
    subject: '数学一',
    type: 'essay',
    no: 0,
    stem: "解线性方程组：x + y = 3，x − y = 1。",
    parts: [{ no: "", prompt: "", answer: "两式相加得 2x=4 → x=2；代入得 y=1。答案：x=2, y=1。" }],
    analysis: "两式相加得 2x=4 → x=2；代入得 y=1。答案：x=2, y=1。",
    tags: ["数学解答", "线代"],
    source: 'practice' },
  { id: "pg_mathp_009",
    year: 2026,
    subject: '数学一',
    type: 'essay',
    no: 0,
    stem: "求矩阵 A = [1 2; 3 4] 的行列式。",
    parts: [{ no: "", prompt: "", answer: "det A = 1×4 − 2×3 = 4 − 6 = −2。答案：−2。" }],
    analysis: "det A = 1×4 − 2×3 = 4 − 6 = −2。答案：−2。",
    tags: ["数学解答", "线代"],
    source: 'practice' },
  { id: "pg_mathp_010",
    year: 2026,
    subject: '数学一',
    type: 'essay',
    no: 0,
    stem: "求矩阵 A = [1 2; 3 4] 的逆矩阵。",
    parts: [{ no: "", prompt: "", answer: "det=−2，A⁻¹ = (1/det)·[4 −2; −3 1] = [−2 1; 3/2 −1/2]。答案：A⁻¹ = [−2 1; 1.5 −0.5]。" }],
    analysis: "det=−2，A⁻¹ = (1/det)·[4 −2; −3 1] = [−2 1; 3/2 −1/2]。答案：A⁻¹ = [−2 1; 1.5 −0.5]。",
    tags: ["数学解答", "线代"],
    source: 'practice' },
  { id: "pg_mathp_011",
    year: 2026,
    subject: '数学一',
    type: 'essay',
    no: 0,
    stem: "判断向量组 α₁=(1,0), α₂=(0,1) 是否线性相关。",
    parts: [{ no: "", prompt: "", answer: "k₁α₁+k₂α₂=0 即 (k₁,k₂)=0 → k₁=k₂=0，只有零解，故线性无关。答案：线性无关。" }],
    analysis: "k₁α₁+k₂α₂=0 即 (k₁,k₂)=0 → k₁=k₂=0，只有零解，故线性无关。答案：线性无关。",
    tags: ["数学解答", "线代"],
    source: 'practice' },
  { id: "pg_mathp_012",
    year: 2026,
    subject: '数学一',
    type: 'essay',
    no: 0,
    stem: "求对角矩阵 A = [2 0; 0 3] 的特征值。",
    parts: [{ no: "", prompt: "", answer: "特征方程为 det(A−λI)=(2−λ)(3−λ)=0，特征值 λ=2, 3。答案：2 和 3。" }],
    analysis: "特征方程为 det(A−λI)=(2−λ)(3−λ)=0，特征值 λ=2, 3。答案：2 和 3。",
    tags: ["数学解答", "线代"],
    source: 'practice' },
  { id: "pg_mathp_013",
    year: 2026,
    subject: '数学一',
    type: 'essay',
    no: 0,
    stem: "判断二次型 f = x₁² + 2x₂² 的正定性。",
    parts: [{ no: "", prompt: "", answer: "对应矩阵 [1 0; 0 2]，顺序主子式均为正（1>0, 2>0），故正定。答案：正定二次型。" }],
    analysis: "对应矩阵 [1 0; 0 2]，顺序主子式均为正（1>0, 2>0），故正定。答案：正定二次型。",
    tags: ["数学解答", "线代"],
    source: 'practice' },
  { id: "pg_mathp_014",
    year: 2026,
    subject: '数学一',
    type: 'essay',
    no: 0,
    stem: "求矩阵 A = [1 2 3; 2 4 6; 1 1 1] 的秩。",
    parts: [{ no: "", prompt: "", answer: "第 2 行 = 2×第 1 行，消去后得 [1 2 3; 0 0 0; 0 −1 −2]，存在 2 个非零行且不成比例，r(A)=2。答案：秩为 2。" }],
    analysis: "第 2 行 = 2×第 1 行，消去后得 [1 2 3; 0 0 0; 0 −1 −2]，存在 2 个非零行且不成比例，r(A)=2。答案：秩为 2。",
    tags: ["数学解答", "线代"],
    source: 'practice' },
  { id: "pg_mathp_015",
    year: 2026,
    subject: '数学一',
    type: 'essay',
    no: 0,
    stem: "求齐次方程组 x + y = 0 的解空间维数。",
    parts: [{ no: "", prompt: "", answer: "1 个方程 2 个未知数，基础解系含 2−1=1 个向量，解空间维数为 1。答案：1。" }],
    analysis: "1 个方程 2 个未知数，基础解系含 2−1=1 个向量，解空间维数为 1。答案：1。",
    tags: ["数学解答", "线代"],
    source: 'practice' },
  { id: "pg_mathp_016",
    year: 2026,
    subject: '数学一',
    type: 'essay',
    no: 0,
    stem: "连续抛掷一枚均匀硬币两次，求两次都出现正面的概率。",
    parts: [{ no: "", prompt: "", answer: "每次正面概率 1/2，独立：P = (1/2)·(1/2) = 1/4。答案：1/4。" }],
    analysis: "每次正面概率 1/2，独立：P = (1/2)·(1/2) = 1/4。答案：1/4。",
    tags: ["数学解答", "概率"],
    source: 'practice' },
  { id: "pg_mathp_017",
    year: 2026,
    subject: '数学一',
    type: 'essay',
    no: 0,
    stem: "掷一枚均匀骰子，求点数大于 4 的概率。",
    parts: [{ no: "", prompt: "", answer: "点数 5、6 满足，共 2 个；P = 2/6 = 1/3。答案：1/3。" }],
    analysis: "点数 5、6 满足，共 2 个；P = 2/6 = 1/3。答案：1/3。",
    tags: ["数学解答", "概率"],
    source: 'practice' },
  { id: "pg_mathp_018",
    year: 2026,
    subject: '数学一',
    type: 'essay',
    no: 0,
    stem: "盒中有 3 个红球 2 个白球，不放回连取两球，求两球都是红球的概率。",
    parts: [{ no: "", prompt: "", answer: "P = (3/5)·(2/4) = 6/20 = 3/10。答案：3/10。" }],
    analysis: "P = (3/5)·(2/4) = 6/20 = 3/10。答案：3/10。",
    tags: ["数学解答", "概率"],
    source: 'practice' },
  { id: "pg_mathp_019",
    year: 2026,
    subject: '数学一',
    type: 'essay',
    no: 0,
    stem: "设 X ~ B(4, 0.5)（二项分布），求 E(X)。",
    parts: [{ no: "", prompt: "", answer: "二项分布期望 E(X)=np = 4×0.5 = 2。答案：2。" }],
    analysis: "二项分布期望 E(X)=np = 4×0.5 = 2。答案：2。",
    tags: ["数学解答", "概率"],
    source: 'practice' },
  { id: "pg_mathp_020",
    year: 2026,
    subject: '数学一',
    type: 'essay',
    no: 0,
    stem: "设 X 在 [0, 2] 上服从均匀分布，求 D(X)。",
    parts: [{ no: "", prompt: "", answer: "均匀分布 U(a,b) 方差 D(X)=(b−a)²/12 = 4/12 = 1/3。答案：1/3。" }],
    analysis: "均匀分布 U(a,b) 方差 D(X)=(b−a)²/12 = 4/12 = 1/3。答案：1/3。",
    tags: ["数学解答", "概率"],
    source: 'practice' },
  { id: "pg_mathp_021",
    year: 2026,
    subject: '数学一',
    type: 'essay',
    no: 0,
    stem: "设 X ~ N(0, 1)，求 P(X < 0)。",
    parts: [{ no: "", prompt: "", answer: "标准正态分布关于 0 对称，P(X<0)=1/2。答案：1/2。" }],
    analysis: "标准正态分布关于 0 对称，P(X<0)=1/2。答案：1/2。",
    tags: ["数学解答", "概率"],
    source: 'practice' },
  { id: "pg_mathp_022",
    year: 2026,
    subject: '数学一',
    type: 'essay',
    no: 0,
    stem: "设 X ~ B(n, p)，写出 D(X) 的公式并说明意义。",
    parts: [{ no: "", prompt: "", answer: "D(X) = np(1−p)，反映取值偏离期望的波动程度。答案：np(1−p)。" }],
    analysis: "D(X) = np(1−p)，反映取值偏离期望的波动程度。答案：np(1−p)。",
    tags: ["数学解答", "概率"],
    source: 'practice' },
  { id: "pg_mathp_023",
    year: 2026,
    subject: '数学一',
    type: 'essay',
    no: 0,
    stem: "设某设备寿命 X 服从参数 λ=1/1000 的指数分布（单位小时），求平均寿命 E(X)。",
    parts: [{ no: "", prompt: "", answer: "指数分布 E(X)=1/λ = 1000 小时。答案：1000 小时。" }],
    analysis: "指数分布 E(X)=1/λ = 1000 小时。答案：1000 小时。",
    tags: ["数学解答", "概率"],
    source: 'practice' },
]
