// qbankMathGen.js —— 数学一模拟题（参数化生成，答案由计算得出，勿手改）
export const PRACTICE_MATH = [
  { id: "pg_math_lim000",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "求极限 lim(x→0) sin(6x)/x 的值。",
    options: ["6", "12", "1", "3"],
    answer: "A",
    analysis: "由重要极限 lim(x→0) sin(ax)/x = a，故结果为 6。",
    tags: ["极限"],
    source: 'practice' },
  { id: "pg_math_lim001",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "求极限 lim(x→0) sin(2x)/x 的值。",
    options: ["2", "4", "1", "1"],
    answer: "A",
    analysis: "由重要极限 lim(x→0) sin(ax)/x = a，故结果为 2。",
    tags: ["极限"],
    source: 'practice' },
  { id: "pg_math_lim002",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "求极限 lim(x→0) sin(4x)/x 的值。",
    options: ["4", "8", "1", "2"],
    answer: "A",
    analysis: "由重要极限 lim(x→0) sin(ax)/x = a，故结果为 4。",
    tags: ["极限"],
    source: 'practice' },
  { id: "pg_math_lim003",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "求极限 lim(x→0) sin(6x)/x 的值。",
    options: ["6", "12", "1", "3"],
    answer: "A",
    analysis: "由重要极限 lim(x→0) sin(ax)/x = a，故结果为 6。",
    tags: ["极限"],
    source: 'practice' },
  { id: "pg_math_lim004",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "求极限 lim(x→0) sin(3x)/x 的值。",
    options: ["3", "6", "1", "1"],
    answer: "A",
    analysis: "由重要极限 lim(x→0) sin(ax)/x = a，故结果为 3。",
    tags: ["极限"],
    source: 'practice' },
  { id: "pg_math_lim005",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "求极限 lim(x→0) sin(2x)/x 的值。",
    options: ["2", "4", "1", "1"],
    answer: "A",
    analysis: "由重要极限 lim(x→0) sin(ax)/x = a，故结果为 2。",
    tags: ["极限"],
    source: 'practice' },
  { id: "pg_math_lim006",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "求极限 lim(x→0) sin(3x)/x 的值。",
    options: ["3", "6", "1", "1"],
    answer: "A",
    analysis: "由重要极限 lim(x→0) sin(ax)/x = a，故结果为 3。",
    tags: ["极限"],
    source: 'practice' },
  { id: "pg_math_lim007",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "求极限 lim(x→0) sin(5x)/x 的值。",
    options: ["5", "10", "1", "2"],
    answer: "A",
    analysis: "由重要极限 lim(x→0) sin(ax)/x = a，故结果为 5。",
    tags: ["极限"],
    source: 'practice' },
  { id: "pg_math_lim008",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "求极限 lim(x→0) sin(3x)/x 的值。",
    options: ["3", "6", "1", "1"],
    answer: "A",
    analysis: "由重要极限 lim(x→0) sin(ax)/x = a，故结果为 3。",
    tags: ["极限"],
    source: 'practice' },
  { id: "pg_math_lim009",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "求极限 lim(x→0) sin(6x)/x 的值。",
    options: ["6", "12", "1", "3"],
    answer: "A",
    analysis: "由重要极限 lim(x→0) sin(ax)/x = a，故结果为 6。",
    tags: ["极限"],
    source: 'practice' },
  { id: "pg_math_lim010",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "求极限 lim(x→0) sin(2x)/x 的值。",
    options: ["2", "4", "1", "1"],
    answer: "A",
    analysis: "由重要极限 lim(x→0) sin(ax)/x = a，故结果为 2。",
    tags: ["极限"],
    source: 'practice' },
  { id: "pg_math_lim011",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "求极限 lim(x→0) sin(5x)/x 的值。",
    options: ["5", "10", "1", "2"],
    answer: "A",
    analysis: "由重要极限 lim(x→0) sin(ax)/x = a，故结果为 5。",
    tags: ["极限"],
    source: 'practice' },
  { id: "pg_math_der000",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "设 f(x)=x^3，则 f'(1)=（  ）。",
    options: ["3", "2", "4", "6"],
    answer: "A",
    analysis: "f'(x)=n·x^(n-1)，f'(1)=3。",
    tags: ["导数"],
    source: 'practice' },
  { id: "pg_math_der001",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "设 f(x)=x^6，则 f'(1)=（  ）。",
    options: ["6", "5", "7", "12"],
    answer: "A",
    analysis: "f'(x)=n·x^(n-1)，f'(1)=6。",
    tags: ["导数"],
    source: 'practice' },
  { id: "pg_math_der002",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "设 f(x)=x^2，则 f'(1)=（  ）。",
    options: ["2", "1", "3", "4"],
    answer: "A",
    analysis: "f'(x)=n·x^(n-1)，f'(1)=2。",
    tags: ["导数"],
    source: 'practice' },
  { id: "pg_math_der003",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "设 f(x)=x^5，则 f'(1)=（  ）。",
    options: ["5", "4", "6", "10"],
    answer: "A",
    analysis: "f'(x)=n·x^(n-1)，f'(1)=5。",
    tags: ["导数"],
    source: 'practice' },
  { id: "pg_math_der004",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "设 f(x)=x^4，则 f'(1)=（  ）。",
    options: ["4", "3", "5", "8"],
    answer: "A",
    analysis: "f'(x)=n·x^(n-1)，f'(1)=4。",
    tags: ["导数"],
    source: 'practice' },
  { id: "pg_math_der005",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "设 f(x)=x^2，则 f'(1)=（  ）。",
    options: ["2", "1", "3", "4"],
    answer: "A",
    analysis: "f'(x)=n·x^(n-1)，f'(1)=2。",
    tags: ["导数"],
    source: 'practice' },
  { id: "pg_math_der006",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "设 f(x)=x^7，则 f'(1)=（  ）。",
    options: ["7", "6", "8", "14"],
    answer: "A",
    analysis: "f'(x)=n·x^(n-1)，f'(1)=7。",
    tags: ["导数"],
    source: 'practice' },
  { id: "pg_math_der007",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "设 f(x)=x^5，则 f'(1)=（  ）。",
    options: ["5", "4", "6", "10"],
    answer: "A",
    analysis: "f'(x)=n·x^(n-1)，f'(1)=5。",
    tags: ["导数"],
    source: 'practice' },
  { id: "pg_math_der008",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "设 f(x)=x^7，则 f'(1)=（  ）。",
    options: ["7", "6", "8", "14"],
    answer: "A",
    analysis: "f'(x)=n·x^(n-1)，f'(1)=7。",
    tags: ["导数"],
    source: 'practice' },
  { id: "pg_math_der009",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "设 f(x)=x^5，则 f'(1)=（  ）。",
    options: ["5", "4", "6", "10"],
    answer: "A",
    analysis: "f'(x)=n·x^(n-1)，f'(1)=5。",
    tags: ["导数"],
    source: 'practice' },
  { id: "pg_math_der010",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "设 f(x)=x^5，则 f'(1)=（  ）。",
    options: ["5", "4", "6", "10"],
    answer: "A",
    analysis: "f'(x)=n·x^(n-1)，f'(1)=5。",
    tags: ["导数"],
    source: 'practice' },
  { id: "pg_math_der011",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "设 f(x)=x^7，则 f'(1)=（  ）。",
    options: ["7", "6", "8", "14"],
    answer: "A",
    analysis: "f'(x)=n·x^(n-1)，f'(1)=7。",
    tags: ["导数"],
    source: 'practice' },
  { id: "pg_math_int000",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "计算定积分 ∫₀¹ x^4 dx 的值。",
    options: ["1/5", "1/4", "5", "4"],
    answer: "A",
    analysis: "∫₀¹ x^n dx = 1/(n+1) = 1/5。",
    tags: ["定积分"],
    source: 'practice' },
  { id: "pg_math_int001",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "计算定积分 ∫₀¹ x^3 dx 的值。",
    options: ["1/4", "1/3", "4", "3"],
    answer: "A",
    analysis: "∫₀¹ x^n dx = 1/(n+1) = 1/4。",
    tags: ["定积分"],
    source: 'practice' },
  { id: "pg_math_int002",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "计算定积分 ∫₀¹ x^5 dx 的值。",
    options: ["1/6", "1/5", "6", "5"],
    answer: "A",
    analysis: "∫₀¹ x^n dx = 1/(n+1) = 1/6。",
    tags: ["定积分"],
    source: 'practice' },
  { id: "pg_math_int003",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "计算定积分 ∫₀¹ x^2 dx 的值。",
    options: ["1/3", "1/2", "3", "2"],
    answer: "A",
    analysis: "∫₀¹ x^n dx = 1/(n+1) = 1/3。",
    tags: ["定积分"],
    source: 'practice' },
  { id: "pg_math_int004",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "计算定积分 ∫₀¹ x^2 dx 的值。",
    options: ["1/3", "1/2", "3", "2"],
    answer: "A",
    analysis: "∫₀¹ x^n dx = 1/(n+1) = 1/3。",
    tags: ["定积分"],
    source: 'practice' },
  { id: "pg_math_int005",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "计算定积分 ∫₀¹ x^2 dx 的值。",
    options: ["1/3", "1/2", "3", "2"],
    answer: "A",
    analysis: "∫₀¹ x^n dx = 1/(n+1) = 1/3。",
    tags: ["定积分"],
    source: 'practice' },
  { id: "pg_math_int006",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "计算定积分 ∫₀¹ x^3 dx 的值。",
    options: ["1/4", "1/3", "4", "3"],
    answer: "A",
    analysis: "∫₀¹ x^n dx = 1/(n+1) = 1/4。",
    tags: ["定积分"],
    source: 'practice' },
  { id: "pg_math_int007",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "计算定积分 ∫₀¹ x^5 dx 的值。",
    options: ["1/6", "1/5", "6", "5"],
    answer: "A",
    analysis: "∫₀¹ x^n dx = 1/(n+1) = 1/6。",
    tags: ["定积分"],
    source: 'practice' },
  { id: "pg_math_int008",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "计算定积分 ∫₀¹ x^2 dx 的值。",
    options: ["1/3", "1/2", "3", "2"],
    answer: "A",
    analysis: "∫₀¹ x^n dx = 1/(n+1) = 1/3。",
    tags: ["定积分"],
    source: 'practice' },
  { id: "pg_math_int009",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "计算定积分 ∫₀¹ x^3 dx 的值。",
    options: ["1/4", "1/3", "4", "3"],
    answer: "A",
    analysis: "∫₀¹ x^n dx = 1/(n+1) = 1/4。",
    tags: ["定积分"],
    source: 'practice' },
  { id: "pg_math_int010",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "计算定积分 ∫₀¹ x^4 dx 的值。",
    options: ["1/5", "1/4", "5", "4"],
    answer: "A",
    analysis: "∫₀¹ x^n dx = 1/(n+1) = 1/5。",
    tags: ["定积分"],
    source: 'practice' },
  { id: "pg_math_int011",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "计算定积分 ∫₀¹ x^5 dx 的值。",
    options: ["1/6", "1/5", "6", "5"],
    answer: "A",
    analysis: "∫₀¹ x^n dx = 1/(n+1) = 1/6。",
    tags: ["定积分"],
    source: 'practice' },
  { id: "pg_math_seq000",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "设数列 a_n = 1/n^2，求级数 1+1/4+1/9+...（p=2 级数收敛性）：该级数（  ）。",
    options: ["收敛", "发散", "条件收敛", "无法判断"],
    answer: "A",
    analysis: "p 级数 Σ1/n^p 当 p>1 时收敛，此处 p=2>1，故收敛。",
    tags: ["级数"],
    source: 'practice' },
  { id: "pg_math_seq001",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "设数列 a_n = 1/n^2，求级数 1+1/4+1/9+...（p=2 级数收敛性）：该级数（  ）。",
    options: ["收敛", "发散", "条件收敛", "无法判断"],
    answer: "A",
    analysis: "p 级数 Σ1/n^p 当 p>1 时收敛，此处 p=2>1，故收敛。",
    tags: ["级数"],
    source: 'practice' },
  { id: "pg_math_seq002",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "设数列 a_n = 1/n^2，求级数 1+1/4+1/9+...（p=2 级数收敛性）：该级数（  ）。",
    options: ["收敛", "发散", "条件收敛", "无法判断"],
    answer: "A",
    analysis: "p 级数 Σ1/n^p 当 p>1 时收敛，此处 p=2>1，故收敛。",
    tags: ["级数"],
    source: 'practice' },
  { id: "pg_math_seq003",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "设数列 a_n = 1/n^2，求级数 1+1/4+1/9+...（p=2 级数收敛性）：该级数（  ）。",
    options: ["收敛", "发散", "条件收敛", "无法判断"],
    answer: "A",
    analysis: "p 级数 Σ1/n^p 当 p>1 时收敛，此处 p=2>1，故收敛。",
    tags: ["级数"],
    source: 'practice' },
  { id: "pg_math_seq004",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "设数列 a_n = 1/n^2，求级数 1+1/4+1/9+...（p=2 级数收敛性）：该级数（  ）。",
    options: ["收敛", "发散", "条件收敛", "无法判断"],
    answer: "A",
    analysis: "p 级数 Σ1/n^p 当 p>1 时收敛，此处 p=2>1，故收敛。",
    tags: ["级数"],
    source: 'practice' },
  { id: "pg_math_seq005",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "设数列 a_n = 1/n^2，求级数 1+1/4+1/9+...（p=2 级数收敛性）：该级数（  ）。",
    options: ["收敛", "发散", "条件收敛", "无法判断"],
    answer: "A",
    analysis: "p 级数 Σ1/n^p 当 p>1 时收敛，此处 p=2>1，故收敛。",
    tags: ["级数"],
    source: 'practice' },
  { id: "pg_math_seq006",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "设数列 a_n = 1/n^2，求级数 1+1/4+1/9+...（p=2 级数收敛性）：该级数（  ）。",
    options: ["收敛", "发散", "条件收敛", "无法判断"],
    answer: "A",
    analysis: "p 级数 Σ1/n^p 当 p>1 时收敛，此处 p=2>1，故收敛。",
    tags: ["级数"],
    source: 'practice' },
  { id: "pg_math_seq007",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "设数列 a_n = 1/n^2，求级数 1+1/4+1/9+...（p=2 级数收敛性）：该级数（  ）。",
    options: ["收敛", "发散", "条件收敛", "无法判断"],
    answer: "A",
    analysis: "p 级数 Σ1/n^p 当 p>1 时收敛，此处 p=2>1，故收敛。",
    tags: ["级数"],
    source: 'practice' },
  { id: "pg_math_seq008",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "设数列 a_n = 1/n^2，求级数 1+1/4+1/9+...（p=2 级数收敛性）：该级数（  ）。",
    options: ["收敛", "发散", "条件收敛", "无法判断"],
    answer: "A",
    analysis: "p 级数 Σ1/n^p 当 p>1 时收敛，此处 p=2>1，故收敛。",
    tags: ["级数"],
    source: 'practice' },
  { id: "pg_math_seq009",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "设数列 a_n = 1/n^2，求级数 1+1/4+1/9+...（p=2 级数收敛性）：该级数（  ）。",
    options: ["收敛", "发散", "条件收敛", "无法判断"],
    answer: "A",
    analysis: "p 级数 Σ1/n^p 当 p>1 时收敛，此处 p=2>1，故收敛。",
    tags: ["级数"],
    source: 'practice' },
  { id: "pg_math_seq010",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "设数列 a_n = 1/n^2，求级数 1+1/4+1/9+...（p=2 级数收敛性）：该级数（  ）。",
    options: ["收敛", "发散", "条件收敛", "无法判断"],
    answer: "A",
    analysis: "p 级数 Σ1/n^p 当 p>1 时收敛，此处 p=2>1，故收敛。",
    tags: ["级数"],
    source: 'practice' },
  { id: "pg_math_seq011",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "设数列 a_n = 1/n^2，求级数 1+1/4+1/9+...（p=2 级数收敛性）：该级数（  ）。",
    options: ["收敛", "发散", "条件收敛", "无法判断"],
    answer: "A",
    analysis: "p 级数 Σ1/n^p 当 p>1 时收敛，此处 p=2>1，故收敛。",
    tags: ["级数"],
    source: 'practice' },
  { id: "pg_math_mat000",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "计算二阶行列式 |1 4; 1 6| 的值。",
    options: ["2", "-2", "3", "1"],
    answer: "A",
    analysis: "行列式 = a·d - b·c = 1×6 - 4×1 = 2。",
    tags: ["行列式"],
    source: 'practice' },
  { id: "pg_math_mat001",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "计算二阶行列式 |3 4; 3 4| 的值。",
    options: ["0", "0", "1", "-1"],
    answer: "A",
    analysis: "行列式 = a·d - b·c = 3×4 - 4×3 = 0。",
    tags: ["行列式"],
    source: 'practice' },
  { id: "pg_math_mat002",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "计算二阶行列式 |3 5; 1 6| 的值。",
    options: ["13", "-13", "14", "12"],
    answer: "A",
    analysis: "行列式 = a·d - b·c = 3×6 - 5×1 = 13。",
    tags: ["行列式"],
    source: 'practice' },
  { id: "pg_math_mat003",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "计算二阶行列式 |2 3; 3 6| 的值。",
    options: ["3", "-3", "4", "2"],
    answer: "A",
    analysis: "行列式 = a·d - b·c = 2×6 - 3×3 = 3。",
    tags: ["行列式"],
    source: 'practice' },
  { id: "pg_math_mat004",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "计算二阶行列式 |3 3; 3 2| 的值。",
    options: ["-3", "3", "-2", "-4"],
    answer: "A",
    analysis: "行列式 = a·d - b·c = 3×2 - 3×3 = -3。",
    tags: ["行列式"],
    source: 'practice' },
  { id: "pg_math_mat005",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "计算二阶行列式 |1 3; 2 6| 的值。",
    options: ["0", "0", "1", "-1"],
    answer: "A",
    analysis: "行列式 = a·d - b·c = 1×6 - 3×2 = 0。",
    tags: ["行列式"],
    source: 'practice' },
  { id: "pg_math_mat006",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "计算二阶行列式 |1 3; 3 2| 的值。",
    options: ["-7", "7", "-6", "-8"],
    answer: "A",
    analysis: "行列式 = a·d - b·c = 1×2 - 3×3 = -7。",
    tags: ["行列式"],
    source: 'practice' },
  { id: "pg_math_mat007",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "计算二阶行列式 |1 5; 3 6| 的值。",
    options: ["-9", "9", "-8", "-10"],
    answer: "A",
    analysis: "行列式 = a·d - b·c = 1×6 - 5×3 = -9。",
    tags: ["行列式"],
    source: 'practice' },
  { id: "pg_math_mat008",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "计算二阶行列式 |2 5; 2 4| 的值。",
    options: ["-2", "2", "-1", "-3"],
    answer: "A",
    analysis: "行列式 = a·d - b·c = 2×4 - 5×2 = -2。",
    tags: ["行列式"],
    source: 'practice' },
  { id: "pg_math_mat009",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "计算二阶行列式 |4 4; 2 4| 的值。",
    options: ["8", "-8", "9", "7"],
    answer: "A",
    analysis: "行列式 = a·d - b·c = 4×4 - 4×2 = 8。",
    tags: ["行列式"],
    source: 'practice' },
  { id: "pg_math_mat010",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "计算二阶行列式 |2 2; 1 4| 的值。",
    options: ["6", "-6", "7", "5"],
    answer: "A",
    analysis: "行列式 = a·d - b·c = 2×4 - 2×1 = 6。",
    tags: ["行列式"],
    source: 'practice' },
  { id: "pg_math_mat011",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "计算二阶行列式 |1 2; 3 2| 的值。",
    options: ["-4", "4", "-3", "-5"],
    answer: "A",
    analysis: "行列式 = a·d - b·c = 1×2 - 2×3 = -4。",
    tags: ["行列式"],
    source: 'practice' },
  { id: "pg_math_mat012",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "计算二阶行列式 |3 3; 1 6| 的值。",
    options: ["15", "-15", "16", "14"],
    answer: "A",
    analysis: "行列式 = a·d - b·c = 3×6 - 3×1 = 15。",
    tags: ["行列式"],
    source: 'practice' },
  { id: "pg_math_mat013",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "计算二阶行列式 |4 3; 3 6| 的值。",
    options: ["15", "-15", "16", "14"],
    answer: "A",
    analysis: "行列式 = a·d - b·c = 4×6 - 3×3 = 15。",
    tags: ["行列式"],
    source: 'practice' },
  { id: "pg_math_rank000",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "设 A 为 3×3 阶矩阵，r(A)=3，则 r(3A)=（  ）。",
    options: ["9", "3", "3", "6"],
    answer: "A",
    analysis: "非零常数乘矩阵不改变秩，r(3A)=r(A)=3。",
    tags: ["矩阵的秩"],
    source: 'practice' },
  { id: "pg_math_rank001",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "设 A 为 3×3 阶矩阵，r(A)=3，则 r(3A)=（  ）。",
    options: ["9", "3", "3", "6"],
    answer: "A",
    analysis: "非零常数乘矩阵不改变秩，r(3A)=r(A)=3。",
    tags: ["矩阵的秩"],
    source: 'practice' },
  { id: "pg_math_rank002",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "设 A 为 2×2 阶矩阵，r(A)=2，则 r(3A)=（  ）。",
    options: ["6", "2", "3", "5"],
    answer: "A",
    analysis: "非零常数乘矩阵不改变秩，r(3A)=r(A)=2。",
    tags: ["矩阵的秩"],
    source: 'practice' },
  { id: "pg_math_rank003",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "设 A 为 3×3 阶矩阵，r(A)=3，则 r(2A)=（  ）。",
    options: ["6", "3", "2", "5"],
    answer: "A",
    analysis: "非零常数乘矩阵不改变秩，r(2A)=r(A)=3。",
    tags: ["矩阵的秩"],
    source: 'practice' },
  { id: "pg_math_rank004",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "设 A 为 2×2 阶矩阵，r(A)=2，则 r(2A)=（  ）。",
    options: ["4", "2", "2", "4"],
    answer: "A",
    analysis: "非零常数乘矩阵不改变秩，r(2A)=r(A)=2。",
    tags: ["矩阵的秩"],
    source: 'practice' },
  { id: "pg_math_rank005",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "设 A 为 4×4 阶矩阵，r(A)=4，则 r(2A)=（  ）。",
    options: ["8", "4", "2", "6"],
    answer: "A",
    analysis: "非零常数乘矩阵不改变秩，r(2A)=r(A)=4。",
    tags: ["矩阵的秩"],
    source: 'practice' },
  { id: "pg_math_rank006",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "设 A 为 3×3 阶矩阵，r(A)=3，则 r(2A)=（  ）。",
    options: ["6", "3", "2", "5"],
    answer: "A",
    analysis: "非零常数乘矩阵不改变秩，r(2A)=r(A)=3。",
    tags: ["矩阵的秩"],
    source: 'practice' },
  { id: "pg_math_rank007",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "设 A 为 3×3 阶矩阵，r(A)=3，则 r(2A)=（  ）。",
    options: ["6", "3", "2", "5"],
    answer: "A",
    analysis: "非零常数乘矩阵不改变秩，r(2A)=r(A)=3。",
    tags: ["矩阵的秩"],
    source: 'practice' },
  { id: "pg_math_rank008",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "设 A 为 3×3 阶矩阵，r(A)=3，则 r(3A)=（  ）。",
    options: ["9", "3", "3", "6"],
    answer: "A",
    analysis: "非零常数乘矩阵不改变秩，r(3A)=r(A)=3。",
    tags: ["矩阵的秩"],
    source: 'practice' },
  { id: "pg_math_rank009",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "设 A 为 4×4 阶矩阵，r(A)=4，则 r(3A)=（  ）。",
    options: ["12", "4", "3", "7"],
    answer: "A",
    analysis: "非零常数乘矩阵不改变秩，r(3A)=r(A)=4。",
    tags: ["矩阵的秩"],
    source: 'practice' },
  { id: "pg_math_rank010",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "设 A 为 3×3 阶矩阵，r(A)=3，则 r(3A)=（  ）。",
    options: ["9", "3", "3", "6"],
    answer: "A",
    analysis: "非零常数乘矩阵不改变秩，r(3A)=r(A)=3。",
    tags: ["矩阵的秩"],
    source: 'practice' },
  { id: "pg_math_rank011",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "设 A 为 3×3 阶矩阵，r(A)=3，则 r(3A)=（  ）。",
    options: ["9", "3", "3", "6"],
    answer: "A",
    analysis: "非零常数乘矩阵不改变秩，r(3A)=r(A)=3。",
    tags: ["矩阵的秩"],
    source: 'practice' },
  { id: "pg_math_rank012",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "设 A 为 3×3 阶矩阵，r(A)=3，则 r(3A)=（  ）。",
    options: ["9", "3", "3", "6"],
    answer: "A",
    analysis: "非零常数乘矩阵不改变秩，r(3A)=r(A)=3。",
    tags: ["矩阵的秩"],
    source: 'practice' },
  { id: "pg_math_rank013",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "设 A 为 4×4 阶矩阵，r(A)=4，则 r(3A)=（  ）。",
    options: ["12", "4", "3", "7"],
    answer: "A",
    analysis: "非零常数乘矩阵不改变秩，r(3A)=r(A)=4。",
    tags: ["矩阵的秩"],
    source: 'practice' },
  { id: "pg_math_lin000",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "n 维向量组线性无关时，其秩 r=3；该向量组所含向量个数最多为（  ）。",
    options: ["3", "5", "6", "∞"],
    answer: "A",
    analysis: "线性无关向量组的秩等于向量个数，最多 3 个。",
    tags: ["线性相关"],
    source: 'practice' },
  { id: "pg_math_lin001",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "n 维向量组线性无关时，其秩 r=3；该向量组所含向量个数最多为（  ）。",
    options: ["3", "5", "6", "∞"],
    answer: "A",
    analysis: "线性无关向量组的秩等于向量个数，最多 3 个。",
    tags: ["线性相关"],
    source: 'practice' },
  { id: "pg_math_lin002",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "n 维向量组线性无关时，其秩 r=2；该向量组所含向量个数最多为（  ）。",
    options: ["2", "4", "4", "∞"],
    answer: "A",
    analysis: "线性无关向量组的秩等于向量个数，最多 2 个。",
    tags: ["线性相关"],
    source: 'practice' },
  { id: "pg_math_lin003",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "n 维向量组线性无关时，其秩 r=3；该向量组所含向量个数最多为（  ）。",
    options: ["3", "5", "6", "∞"],
    answer: "A",
    analysis: "线性无关向量组的秩等于向量个数，最多 3 个。",
    tags: ["线性相关"],
    source: 'practice' },
  { id: "pg_math_lin004",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "n 维向量组线性无关时，其秩 r=2；该向量组所含向量个数最多为（  ）。",
    options: ["2", "4", "4", "∞"],
    answer: "A",
    analysis: "线性无关向量组的秩等于向量个数，最多 2 个。",
    tags: ["线性相关"],
    source: 'practice' },
  { id: "pg_math_lin005",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "n 维向量组线性无关时，其秩 r=4；该向量组所含向量个数最多为（  ）。",
    options: ["4", "6", "8", "∞"],
    answer: "A",
    analysis: "线性无关向量组的秩等于向量个数，最多 4 个。",
    tags: ["线性相关"],
    source: 'practice' },
  { id: "pg_math_lin006",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "n 维向量组线性无关时，其秩 r=3；该向量组所含向量个数最多为（  ）。",
    options: ["3", "5", "6", "∞"],
    answer: "A",
    analysis: "线性无关向量组的秩等于向量个数，最多 3 个。",
    tags: ["线性相关"],
    source: 'practice' },
  { id: "pg_math_lin007",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "n 维向量组线性无关时，其秩 r=2；该向量组所含向量个数最多为（  ）。",
    options: ["2", "4", "4", "∞"],
    answer: "A",
    analysis: "线性无关向量组的秩等于向量个数，最多 2 个。",
    tags: ["线性相关"],
    source: 'practice' },
  { id: "pg_math_lin008",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "n 维向量组线性无关时，其秩 r=3；该向量组所含向量个数最多为（  ）。",
    options: ["3", "5", "6", "∞"],
    answer: "A",
    analysis: "线性无关向量组的秩等于向量个数，最多 3 个。",
    tags: ["线性相关"],
    source: 'practice' },
  { id: "pg_math_lin009",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "n 维向量组线性无关时，其秩 r=2；该向量组所含向量个数最多为（  ）。",
    options: ["2", "4", "4", "∞"],
    answer: "A",
    analysis: "线性无关向量组的秩等于向量个数，最多 2 个。",
    tags: ["线性相关"],
    source: 'practice' },
  { id: "pg_math_lin010",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "n 维向量组线性无关时，其秩 r=3；该向量组所含向量个数最多为（  ）。",
    options: ["3", "5", "6", "∞"],
    answer: "A",
    analysis: "线性无关向量组的秩等于向量个数，最多 3 个。",
    tags: ["线性相关"],
    source: 'practice' },
  { id: "pg_math_lin011",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "n 维向量组线性无关时，其秩 r=3；该向量组所含向量个数最多为（  ）。",
    options: ["3", "5", "6", "∞"],
    answer: "A",
    analysis: "线性无关向量组的秩等于向量个数，最多 3 个。",
    tags: ["线性相关"],
    source: 'practice' },
  { id: "pg_math_lin012",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "n 维向量组线性无关时，其秩 r=3；该向量组所含向量个数最多为（  ）。",
    options: ["3", "5", "6", "∞"],
    answer: "A",
    analysis: "线性无关向量组的秩等于向量个数，最多 3 个。",
    tags: ["线性相关"],
    source: 'practice' },
  { id: "pg_math_lin013",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "n 维向量组线性无关时，其秩 r=3；该向量组所含向量个数最多为（  ）。",
    options: ["3", "5", "6", "∞"],
    answer: "A",
    analysis: "线性无关向量组的秩等于向量个数，最多 3 个。",
    tags: ["线性相关"],
    source: 'practice' },
  { id: "pg_math_prob000",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "从 1~8 中任取一个整数，取到 3 的倍数的概率为（  ）。",
    options: ["3/8", "8/3", "1/3", "3/9"],
    answer: "A",
    analysis: "1~8 中 3 的倍数恰有 3 个（1×k, 2×k），概率 = 3/8。",
    tags: ["古典概型"],
    source: 'practice' },
  { id: "pg_math_prob001",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "从 1~10 中任取一个整数，取到 3 的倍数的概率为（  ）。",
    options: ["3/10", "10/3", "1/3", "3/11"],
    answer: "A",
    analysis: "1~10 中 3 的倍数恰有 3 个（1×k, 2×k），概率 = 3/10。",
    tags: ["古典概型"],
    source: 'practice' },
  { id: "pg_math_prob002",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "从 1~6 中任取一个整数，取到 2 的倍数的概率为（  ）。",
    options: ["2/6", "6/2", "1/2", "2/7"],
    answer: "A",
    analysis: "1~6 中 2 的倍数恰有 2 个（1×k, 2×k），概率 = 2/6。",
    tags: ["古典概型"],
    source: 'practice' },
  { id: "pg_math_prob003",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "从 1~6 中任取一个整数，取到 2 的倍数的概率为（  ）。",
    options: ["2/6", "6/2", "1/2", "2/7"],
    answer: "A",
    analysis: "1~6 中 2 的倍数恰有 2 个（1×k, 2×k），概率 = 2/6。",
    tags: ["古典概型"],
    source: 'practice' },
  { id: "pg_math_prob004",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "从 1~10 中任取一个整数，取到 2 的倍数的概率为（  ）。",
    options: ["2/10", "10/2", "1/2", "2/11"],
    answer: "A",
    analysis: "1~10 中 2 的倍数恰有 2 个（1×k, 2×k），概率 = 2/10。",
    tags: ["古典概型"],
    source: 'practice' },
  { id: "pg_math_prob005",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "从 1~6 中任取一个整数，取到 2 的倍数的概率为（  ）。",
    options: ["2/6", "6/2", "1/2", "2/7"],
    answer: "A",
    analysis: "1~6 中 2 的倍数恰有 2 个（1×k, 2×k），概率 = 2/6。",
    tags: ["古典概型"],
    source: 'practice' },
  { id: "pg_math_prob006",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "从 1~10 中任取一个整数，取到 3 的倍数的概率为（  ）。",
    options: ["3/10", "10/3", "1/3", "3/11"],
    answer: "A",
    analysis: "1~10 中 3 的倍数恰有 3 个（1×k, 2×k），概率 = 3/10。",
    tags: ["古典概型"],
    source: 'practice' },
  { id: "pg_math_prob007",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "从 1~8 中任取一个整数，取到 2 的倍数的概率为（  ）。",
    options: ["2/8", "8/2", "1/2", "2/9"],
    answer: "A",
    analysis: "1~8 中 2 的倍数恰有 2 个（1×k, 2×k），概率 = 2/8。",
    tags: ["古典概型"],
    source: 'practice' },
  { id: "pg_math_prob008",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "从 1~8 中任取一个整数，取到 3 的倍数的概率为（  ）。",
    options: ["3/8", "8/3", "1/3", "3/9"],
    answer: "A",
    analysis: "1~8 中 3 的倍数恰有 3 个（1×k, 2×k），概率 = 3/8。",
    tags: ["古典概型"],
    source: 'practice' },
  { id: "pg_math_prob009",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "从 1~8 中任取一个整数，取到 2 的倍数的概率为（  ）。",
    options: ["2/8", "8/2", "1/2", "2/9"],
    answer: "A",
    analysis: "1~8 中 2 的倍数恰有 2 个（1×k, 2×k），概率 = 2/8。",
    tags: ["古典概型"],
    source: 'practice' },
  { id: "pg_math_prob010",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "从 1~6 中任取一个整数，取到 4 的倍数的概率为（  ）。",
    options: ["4/6", "6/4", "1/4", "4/7"],
    answer: "A",
    analysis: "1~6 中 4 的倍数恰有 4 个（1×k, 2×k），概率 = 4/6。",
    tags: ["古典概型"],
    source: 'practice' },
  { id: "pg_math_prob011",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "从 1~8 中任取一个整数，取到 3 的倍数的概率为（  ）。",
    options: ["3/8", "8/3", "1/3", "3/9"],
    answer: "A",
    analysis: "1~8 中 3 的倍数恰有 3 个（1×k, 2×k），概率 = 3/8。",
    tags: ["古典概型"],
    source: 'practice' },
  { id: "pg_math_com000",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "从 6 个不同元素中任取 2 个的组合数为（  ）。",
    options: ["15", "16", "14", "30"],
    answer: "A",
    analysis: "C(6,2) = 15。",
    tags: ["组合数"],
    source: 'practice' },
  { id: "pg_math_com001",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "从 5 个不同元素中任取 2 个的组合数为（  ）。",
    options: ["10", "11", "9", "20"],
    answer: "A",
    analysis: "C(5,2) = 10。",
    tags: ["组合数"],
    source: 'practice' },
  { id: "pg_math_com002",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "从 6 个不同元素中任取 2 个的组合数为（  ）。",
    options: ["15", "16", "14", "30"],
    answer: "A",
    analysis: "C(6,2) = 15。",
    tags: ["组合数"],
    source: 'practice' },
  { id: "pg_math_com003",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "从 4 个不同元素中任取 3 个的组合数为（  ）。",
    options: ["4", "5", "3", "8"],
    answer: "A",
    analysis: "C(4,3) = 4。",
    tags: ["组合数"],
    source: 'practice' },
  { id: "pg_math_com004",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "从 4 个不同元素中任取 3 个的组合数为（  ）。",
    options: ["4", "5", "3", "8"],
    answer: "A",
    analysis: "C(4,3) = 4。",
    tags: ["组合数"],
    source: 'practice' },
  { id: "pg_math_com005",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "从 6 个不同元素中任取 2 个的组合数为（  ）。",
    options: ["15", "16", "14", "30"],
    answer: "A",
    analysis: "C(6,2) = 15。",
    tags: ["组合数"],
    source: 'practice' },
  { id: "pg_math_com006",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "从 4 个不同元素中任取 2 个的组合数为（  ）。",
    options: ["6", "7", "5", "12"],
    answer: "A",
    analysis: "C(4,2) = 6。",
    tags: ["组合数"],
    source: 'practice' },
  { id: "pg_math_com007",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "从 5 个不同元素中任取 2 个的组合数为（  ）。",
    options: ["10", "11", "9", "20"],
    answer: "A",
    analysis: "C(5,2) = 10。",
    tags: ["组合数"],
    source: 'practice' },
  { id: "pg_math_com008",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "从 5 个不同元素中任取 2 个的组合数为（  ）。",
    options: ["10", "11", "9", "20"],
    answer: "A",
    analysis: "C(5,2) = 10。",
    tags: ["组合数"],
    source: 'practice' },
  { id: "pg_math_com009",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "从 4 个不同元素中任取 3 个的组合数为（  ）。",
    options: ["4", "5", "3", "8"],
    answer: "A",
    analysis: "C(4,3) = 4。",
    tags: ["组合数"],
    source: 'practice' },
  { id: "pg_math_com010",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "从 6 个不同元素中任取 2 个的组合数为（  ）。",
    options: ["15", "16", "14", "30"],
    answer: "A",
    analysis: "C(6,2) = 15。",
    tags: ["组合数"],
    source: 'practice' },
  { id: "pg_math_com011",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "从 5 个不同元素中任取 3 个的组合数为（  ）。",
    options: ["10", "11", "9", "20"],
    answer: "A",
    analysis: "C(5,3) = 10。",
    tags: ["组合数"],
    source: 'practice' },
  { id: "pg_math_exp000",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "随机变量 X 只取 0、1 两个值，P(X=1)=0.5，则 P(X=0)=（  ）。",
    options: ["0.5", "0.5", "0.6", "1.0"],
    answer: "A",
    analysis: "概率和为 1，P(X=0) = 1 - 0.5 = 0.5。",
    tags: ["概率基本性质"],
    source: 'practice' },
  { id: "pg_math_exp001",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "随机变量 X 只取 0、1 两个值，P(X=1)=0.5，则 P(X=0)=（  ）。",
    options: ["0.5", "0.5", "0.6", "1.0"],
    answer: "A",
    analysis: "概率和为 1，P(X=0) = 1 - 0.5 = 0.5。",
    tags: ["概率基本性质"],
    source: 'practice' },
  { id: "pg_math_exp002",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "随机变量 X 只取 0、1 两个值，P(X=1)=0.4，则 P(X=0)=（  ）。",
    options: ["0.6", "0.4", "0.5", "0.8"],
    answer: "A",
    analysis: "概率和为 1，P(X=0) = 1 - 0.4 = 0.6。",
    tags: ["概率基本性质"],
    source: 'practice' },
  { id: "pg_math_exp003",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "随机变量 X 只取 0、1 两个值，P(X=1)=0.5，则 P(X=0)=（  ）。",
    options: ["0.5", "0.5", "0.6", "1.0"],
    answer: "A",
    analysis: "概率和为 1，P(X=0) = 1 - 0.5 = 0.5。",
    tags: ["概率基本性质"],
    source: 'practice' },
  { id: "pg_math_exp004",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "随机变量 X 只取 0、1 两个值，P(X=1)=0.2，则 P(X=0)=（  ）。",
    options: ["0.8", "0.2", "0.3", "0.4"],
    answer: "A",
    analysis: "概率和为 1，P(X=0) = 1 - 0.2 = 0.8。",
    tags: ["概率基本性质"],
    source: 'practice' },
  { id: "pg_math_exp005",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "随机变量 X 只取 0、1 两个值，P(X=1)=0.4，则 P(X=0)=（  ）。",
    options: ["0.6", "0.4", "0.5", "0.8"],
    answer: "A",
    analysis: "概率和为 1，P(X=0) = 1 - 0.4 = 0.6。",
    tags: ["概率基本性质"],
    source: 'practice' },
  { id: "pg_math_exp006",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "随机变量 X 只取 0、1 两个值，P(X=1)=0.4，则 P(X=0)=（  ）。",
    options: ["0.6", "0.4", "0.5", "0.8"],
    answer: "A",
    analysis: "概率和为 1，P(X=0) = 1 - 0.4 = 0.6。",
    tags: ["概率基本性质"],
    source: 'practice' },
  { id: "pg_math_exp007",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "随机变量 X 只取 0、1 两个值，P(X=1)=0.4，则 P(X=0)=（  ）。",
    options: ["0.6", "0.4", "0.5", "0.8"],
    answer: "A",
    analysis: "概率和为 1，P(X=0) = 1 - 0.4 = 0.6。",
    tags: ["概率基本性质"],
    source: 'practice' },
  { id: "pg_math_exp008",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "随机变量 X 只取 0、1 两个值，P(X=1)=0.2，则 P(X=0)=（  ）。",
    options: ["0.8", "0.2", "0.3", "0.4"],
    answer: "A",
    analysis: "概率和为 1，P(X=0) = 1 - 0.2 = 0.8。",
    tags: ["概率基本性质"],
    source: 'practice' },
  { id: "pg_math_exp009",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "随机变量 X 只取 0、1 两个值，P(X=1)=0.3，则 P(X=0)=（  ）。",
    options: ["0.7", "0.3", "0.4", "0.6"],
    answer: "A",
    analysis: "概率和为 1，P(X=0) = 1 - 0.3 = 0.7。",
    tags: ["概率基本性质"],
    source: 'practice' },
  { id: "pg_math_exp010",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "随机变量 X 只取 0、1 两个值，P(X=1)=0.2，则 P(X=0)=（  ）。",
    options: ["0.8", "0.2", "0.3", "0.4"],
    answer: "A",
    analysis: "概率和为 1，P(X=0) = 1 - 0.2 = 0.8。",
    tags: ["概率基本性质"],
    source: 'practice' },
  { id: "pg_math_exp011",
    year: 2026,
    subject: "数学一",
    type: 'choice',
    no: 0,
    stem: "随机变量 X 只取 0、1 两个值，P(X=1)=0.3，则 P(X=0)=（  ）。",
    options: ["0.7", "0.3", "0.4", "0.6"],
    answer: "A",
    analysis: "概率和为 1，P(X=0) = 1 - 0.3 = 0.7。",
    tags: ["概率基本性质"],
    source: 'practice' },
]
